version: '3'
services:
  db:
    image: mysql:5.7
    container_name: proken-db
    environment:
      MYSQL_ROOT_PASSWORD: prokenec
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    container_name: proken-web
    volumes:
      - .:/proken
    ports:
      - "3000:3000"
    links:
      - db
